### ISSUE TITLE
Workflow isn't working for python 3.6 anymore based on 22.04 requirements

### ISSUE THREAD

**Issue by shawnbohn-pnnl** [csirtgadgets/csirtg-indicator-v3#10]
Looks like the builds are failing on this because of python 3.6 requirements are missing for 22.04.  Probably should be removed, but a bigger issue is if this succeeds WILL the automation make a new docker container for csirtg-fm?

**Comment by wesyoung** [comment]
i forget off hand, i made a note to dive into the workflows a bit and re-wire them (it's been a while).

**Comment by wesyoung** [comment]
3.0.0 was published, seems to work OK. updated the requirements.txt in csirtg-fm-v2 as well. something screwy still going on with the publish action, but was able to manually upload..

**Comment by shawnbohn-pnnl** [comment]
@wesyoung where did you manually upload?  When I look at https://hub.docker.com/u/csirtgadgets I don't see anything newer than three years old.

**Comment by wesyoung** [comment]
https://pypi.org/project/csirtg-indicator/#history

```
% pip install csirtg-indicator==3.0.0
```

**Comment by shawnbohn-pnnl** [comment]
So a couple of issues:  1) the build failed on the packaging and 2) don't you need to update the cif-v5 docker image so that it will build the other docker images?  We noticed that even if you update the package the other docker images aren't being built off the new packages.  Not sure if that is what you intended to have happen or not.

**Comment by shawnbohn-pnnl** [comment]
Hey Wes, So I understand how to get the package, but what about CIF-V5 docker containers getting updated too?  (see prior message)

**Comment by wesyoung** [comment]
hiya (busy summer) - i tried fiddling with the containers a bit, there's something screwy with one of the deeper libraries that breaks the build (feels cython related, which is tough to debug sometimes). at this point i'll probably archive it since python 3.7 is approaching EOL too.. if you've found some useful ideas in there, take them and run with them, i've debated building a v6, but haven't had the time recently..
